version: '3'

services:
  web:
    container_name: django
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/static
  db:
    container_name: postgresdb
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env 
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  staticfiles:
